name: Docker Image CI for GHCR and depedencies

on:
  push:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build and push the image
        run: |
          docker login --username ${{ secrets.GH_USER }} --password ${{ secrets.GH_PAT }} ghcr.io
          docker build . --tag ghcr.io/zoeleve/main-temp:latest
          docker push ghcr.io/zoeleve/main-temp:latest

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Check code formatting with black
        run: |
          poetry run black . --check

      - name: Install requests
        run: |
          pip install requests

      - name: Install python-dotenv
        run: |
          pip install python-dotenv
